name: check diferences between branches
on: push
jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      GIT_DIFF: ${{ steps.diff.outputs.GIT_DIFF }}
    steps:
      - name: Checkout repo
        uses: 'actions/checkout@v2'


      - name: Diff against Develop
        id: diff
        run: |
          GIT_DIFF=$(git rev-list --left-right --pretty=oneline  test/develop...${{GITHUB_HEAD_REF}} | egrep "<")
          if [[ $GIT_DIFF ]]
          then
            echo "You need to Update  yout branch with develop"
          fi
          echo "::set-output name=GIT_DIFF::$GIT_DIFF"


      - name: Check for changes
        id: changes
        if: ${{ steps.diff.outputs.GIT_DIFF }}
        run:
          echo "You need to Update  yout branch with develop "