name: A workflow for my Hello World file
on:
  pull_request:
     branches: [develop]
     types: [ labeled ]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'test')
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "pm3ndoza"
